import re

ERROR_PATTERNS = [
    # --- General timeout and reachability ---
    r"took too long to respond",
    r"connection timed out",
    r"the connection has timed out",
    r"response timed out",
    r"request timeout",
    r"408 request timeout",
    r"timeout",
    r"server took too long to respond",
    r"this page isn't working",
    r"hmmm can't reach this page",
    r"site can't be reached",
    r"site cannot be reached",
    r"unable to connect to the server",
    r"cannot reach the server",
    r"could not connect",
    r"cannot connect to server",
    r"connection failed",
    r"connection aborted",
    r"connection disconnected",
    r"connection was reset",
    r"connection was refused",
    r"network changed",
    r"proxy connection failed",
    r"too many redirects",

    # --- Common HTTP error responses ---
    r"service unavailable",
    r"temporarily unavailable",
    r"bad gateway",
    r"gateway timeout",
    r"http 504",
    r"error 502",
    r"502 bad gateway",
    r"error 503",
    r"503 service unavailable",

    # --- Chrome / Chromium specific error codes ---
    r"err_connection_timed_out",
    r"err_connection_refused",
    r"err_connection_reset",
    r"err_connection_closed",
    r"err_name_not_resolved",
    r"dns_probe_finished_nxdomain",
    r"err_address_unreachable",
    r"err_connection_aborted",
    r"err_connection_disconnected",
    r"err_connection_failed",
    r"err_network_changed",
    r"err_http2_protocol_error",
    r"err_http2_frame_error",
    r"err_too_many_redirects",
    r"net::err_connection_timed_out",
    r"err_ssl_protocol_error",
    r"err_ssl_version_or_cipher_mismatch",
    r"err_ssl_obsolete_version",
    r"err_ssl_weak_server_ephemeral_dh_key",
    r"err_quic_protocol_error",
    r"err_proxy_connection_failed",
    r"err_proxy_connection_refused",

    # --- Localized (non-English) ---
    r"zeitüberschreitung",
    r"verbindungszeitüberschreitung",
    r"server nicht erreichbar",
    r"server reagiert nicht",
    r"verbindung wurde zurückgesetzt",
    r"netzwerk geändert",
]

ERROR_REGEX = re.compile("|".join(ERROR_PATTERNS), re.IGNORECASE)